[package]
name = "estree-parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
phf = { version = "0.10.0", features = ["macros"] }
ucd = "0.1.1"
unicode-segmentation = "1.8.0"
