[package]
name = "typescript-llvm-ir"
version = "0.1.0"
authors = ["Lukas Bombach <lukas.bombach@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"